name: tIGArx
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - h5py
  - mpich=4.2.1
  - mpi4py=3.1.6
  - fenics-dolfinx=0.7.3
  - fenics-libdolfinx=0.7.3
  - fenics-basix=0.7.0
  - fenics-libbasix=0.7.0
  - fenics-ufcx=0.7.0
  - fenics-ufl=2023.2.0
  - scipy
  - numba=0.60.0
  - petsc4py
  - adios2
  - gfortran
  - pip:
      - adios4dolfinx
      - coverage
      - iniconfig
      - pluggy
      - pytest
      - https://github.com/dalcinl/igakit/archive/refs/heads/master.zip