name: tigarx 
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx=0.9.0
  - mpich
  - pyvista
  - scipy
  - numba
  - gfortran
  - pytest
  - sphinx
  - pip
  - pip:
      - https://github.com/dalcinl/igakit/archive/refs/heads/master.zip
